/* jshint esversion: 6 */


module.exports = {
    FB_PAGE_TOKEN: 'asdfjkl;',
    FB_VERIFY_TOKEN: 'EAADqjcqoQfUBAFHsGLJKAxPunV9IGVEWpmu4jfBp3x2cTDsu5yCCUwxOGMu8aOhhWptKwrNUHrnHuMYJuFDD1ZCz9oN53Vmo17ZBmVipkUPld46KsU8dUqamI3ASZCeCkkyXeGbiNZBXAu8Nbl5XaVerySP8XmtmvkgzItNL9wZDZD',
    WIT_TOKEN: '4SEVM5UZWCD3V3QPQJ3HXJCHUFGTHGV5',
};
