/* jshint esversion: 6 */


module.exports = {
    FB_PAGE_TOKEN: 'asdfjkl;',
    FB_VERIFY_TOKEN: 'EAADqjcqoQfUBAJO7VdIluMYBQPbVnOHs0L6t1sV8cifJr5isyNpRW9CboAyZCkIo2g7kA2CUPqVvXnvYKDoyBBiZCDm1ZAI5zyMJ2ftH9Y57okvsOA1ZCf2ZAZAYUSRTDt8P5SIqFUpjlmdKVbCnycZBS0NOPGXDBMVNczhJMavrwZDZD',
    WIT_TOKEN: '4SEVM5UZWCD3V3QPQJ3HXJCHUFGTHGV5',
};
